import type {ImageSourcePropType} from 'react-native';
export const artwork:Record<string,ImageSourcePropType>={
 'paris':require('../assets/brands/paris.png'),
 'starbucks':require('../assets/brands/starbucks.png'),
 'mcdonalds':require('../assets/brands/mcdonalds.png'),
 'papa':require('../assets/brands/papa.png'),
 'outback':require('../assets/brands/outback.png'),
 'burgerking':require('../assets/brands/burgerking.png'),
 'kfc':require('../assets/brands/kfc.png'),
 'cu':require('../assets/brands/cu.jpg'),
 'olive':require('../assets/brands/olive.png'),
 'pink':require('../assets/cards/pink.png'),
 'zero':require('../assets/cards/zero.png'),
 'hilton':require('../assets/cards/hilton.png'),
 'sk':require('../assets/cards/sk.png'),
 'skt':require('../assets/memberships/skt.png'),
 'kt':require('../assets/memberships/kt.png'),
 'lgu':require('../assets/memberships/lgu.png'),
 'happy':require('../assets/memberships/happy.png'),
 'lemoa':require('../assets/identity/lemoa.png'),
};
