import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Modal,ScrollView,Text,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Action,styles,useSession} from './session';
import {request,type Place} from './api';
import {currentPosition} from './location';
export const demoPlaces:Place[]=[{id:'demo-paris',merchantId:'paris',name:'파리바게뜨 테스트점',address:'가상 테스트 건물 1층 (실제 위치 아님)',distance:12,floor:'1층 · 테스트 데이터'},{id:'demo-starbucks',merchantId:'starbucks',name:'스타벅스 테스트점',address:'가상 테스트 건물 2층 (실제 위치 아님)',distance:12,floor:'2층 · 테스트 데이터'},{id:'demo-cu',merchantId:'cu',name:'CU 테스트점',address:'가상 테스트 건물 지하 1층 (실제 위치 아님)',distance:18,floor:'지하 1층 · 테스트 데이터'}];
export default function Nearby({onChoose,onClose}:{onChoose:(place:Place)=>void;onClose:()=>void}){
 const {member,config}=useSession();const [phase,setPhase]=useState<'intro'|'loading'|'list'|'confirm'|'error'>('intro'),[places,setPlaces]=useState<Place[]>([]),[selected,setSelected]=useState<Place|null>(null),[accuracy,setAccuracy]=useState<number|null>(null),[error,setError]=useState(''),[demo,setDemo]=useState(false);
 const generation=useRef(0),key=`lemoa.location-consent.${member!.id}`;
 const locate=useCallback(async()=>{const generationId=++generation.current;setDemo(false);setPhase('loading');setError('');try{if(!config.places)throw new Error('주변 가게 검색 서비스가 아직 연결되지 않았습니다. 직접 가게를 선택해 주세요.');const coords=await currentPosition();if(generation.current!==generationId)return;const result=await request<{places:Place[];accuracy:number}>('/api/places/nearby',coords);if(generation.current!==generationId)return;setPlaces(result.places);setAccuracy(result.accuracy);setSelected(result.places.length===1?result.places[0]:null);setPhase(result.places.length===1?'confirm':'list');}catch(error){if(generation.current===generationId){setError(error instanceof Error?error.message:'위치를 확인하지 못했습니다.');setPhase('error');}}},[config.places]);
 useEffect(()=>{let alive=true;const tracker=generation;AsyncStorage.getItem(key).then(value=>{if(alive&&value==='yes'&&config.places)void locate();}).catch(()=>{});return()=>{alive=false;tracker.current++;};},[key,config.places,locate]);
 const close=()=>{generation.current++;onClose();};
 const sample=(single:boolean)=>{generation.current++;setDemo(true);setAccuracy(single?10:180);const list=single?demoPlaces.slice(0,1):demoPlaces;setPlaces(list);setSelected(single?list[0]:null);setPhase(single?'confirm':'list');};
 return <Modal transparent animationType="fade" onRequestClose={close}><View style={{flex:1,backgroundColor:'#28203380',justifyContent:'center',alignItems:'center',padding:20}}><View style={{backgroundColor:'#FFF',borderRadius:22,padding:22,width:'100%',maxWidth:500,maxHeight:'90%',gap:14}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:14}}><Text accessibilityRole="header" style={styles.title}>{phase==='confirm'?'이 가게가 맞나요?':'지금 방문한 가게 찾기'}</Text>{demo&&<Text style={styles.error}>관리자 테스트 · 실제 GPS 검색 결과가 아닙니다.</Text>}{phase==='intro'&&<><Text style={styles.copy}>앱을 사용할 때 현재 위치로 지원 가게 9개 브랜드의 주변 지점을 찾습니다. 위치는 르모아 서버를 거쳐 카카오 장소 검색으로 전달되며, 르모아는 위치·이동 기록을 저장하지 않습니다. GPS로 층을 구분할 수 없으므로 방문 가게는 직접 확인해 주세요.</Text>{config.places?<Action title="동의하고 현재 위치로 찾기" onPress={()=>{void AsyncStorage.setItem(key,'yes').catch(()=>{});void locate();}}/>:<Text style={styles.error}>장소 검색 서비스 연결 전입니다. 현재는 직접 가게를 선택할 수 있어요.</Text>}</>}{phase==='loading'&&<><ActivityIndicator color="#796292"/><Text style={styles.copy}>현재 위치와 주변 지점을 확인하고 있어요…</Text></>}{phase==='error'&&<><Text accessibilityRole="alert" style={styles.error}>{error}</Text>{config.places&&<Action title="위치 다시 확인" onPress={()=>void locate()}/>}</>}{(phase==='list'||phase==='confirm')&&<>{accuracy!==null&&<Text style={styles.copy}>위치 오차 약 {Math.round(accuracy)}m · 층 구분 불가{accuracy>80?' · 위치 정확도가 낮아 직접 선택이 필요합니다.':''}</Text>}{phase==='list'&&<><Text style={styles.copy}>{places.length?'같은 건물이나 가까운 가게가 여러 곳일 수 있어요. 지점명과 주소를 보고 선택하세요.':'주변에서 지원 가게를 찾지 못했습니다. 직접 검색하거나 위치를 다시 확인해 주세요.'}</Text>{places.map(place=><View key={place.id} style={styles.notice}><Text style={{fontSize:17,fontWeight:'700'}}>{place.name}</Text><Text style={styles.copy}>{place.address}{ '\n'}약 {place.distance}m · {place.floor}</Text><Action title={`${place.name} 선택`} secondary onPress={()=>{setSelected(place);setPhase('confirm');}}/></View>)}</>}{phase==='confirm'&&selected&&<View style={styles.notice}><Text style={{fontSize:19,fontWeight:'700'}}>{selected.name}</Text><Text style={styles.copy}>{selected.address}{ '\n'}약 {selected.distance}m · {selected.floor}</Text><Action title="맞아요 · 멤버십 혜택 보기" onPress={()=>{generation.current++;onChoose(selected);}}/><Action title="다른 가게 선택" secondary onPress={()=>setPhase('list')}/></View>}{config.places&&<Action title="위치 다시 확인" secondary onPress={()=>void locate()}/>}</>}{member?.role==='admin'&&<View style={styles.notice}><Text style={styles.copy}>관리자 시나리오 테스트 (위치 권한·외부 API 불필요)</Text><Action title="테스트: 가까운 가게 1곳" secondary onPress={()=>sample(true)}/><Action title="테스트: 위치 오차·여러 층 가게" secondary onPress={()=>sample(false)}/></View>}</ScrollView><Action title="가게 직접 선택하기" secondary onPress={close}/></View></View></Modal>;
}
