import React,{createContext,useContext,useEffect,useState} from 'react';
import {ActivityIndicator,Image,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {request,restoreToken,passwordLogin,socialLogin,type Member,type ServiceConfig} from './api';
import {artwork} from './artwork';
export const Session=createContext<{member:Member|null;setMember:(member:Member|null)=>void;config:ServiceConfig}>({member:null,setMember:()=>{},config:{providers:{google:false,naver:false},places:false,localAdmin:false}});
export const useSession=()=>useContext(Session);
export function SessionProvider({children}:{children:React.ReactNode}){
 const [member,setMember]=useState<Member|null>(null),[config,setConfig]=useState<ServiceConfig>({providers:{google:false,naver:false},places:false,localAdmin:false});
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;async function load(){try{await restoreToken();const [settings,result]=await Promise.all([request<ServiceConfig>('/api/config'),request<{user:Member|null}>('/api/auth/me')]);if(active){setConfig(settings);setMember(result.user);setReady(true);setError('');}}catch{if(active)setError('회원 서버에 연결하지 못했습니다. 서버가 실행 중인지 확인해 주세요.');}}void load();return()=>{active=false;};},[attempt]);
 if(!ready)return <View style={styles.center}>{error?<><Text style={styles.copy}>{error}</Text><Action title="다시 연결" onPress={()=>{setError('');setAttempt(x=>x+1);}}/></>:<><ActivityIndicator/><Text>르모아를 준비하고 있어요</Text></>}</View>;
 return <Session.Provider value={{member,setMember,config}}>{children}</Session.Provider>;
}
export function Action({title,onPress,disabled=false,secondary=false}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} disabled={disabled} style={[styles.button,secondary&&styles.secondary,disabled&&{opacity:.5}]}><Text style={[styles.buttonText,secondary&&{color:'#70548D'}]}>{title}</Text></Pressable>;}
export function AuthScreen(){
 const {config,setMember}=useSession();const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(provider?:'google'|'naver'){
 setError('');if((signup||provider)&&!consent){setError('필수 정보 처리 안내를 확인해 주세요.');return;}
 if(provider&&!config.providers[provider]){setError(`${provider==='naver'?'네이버':'구글'} 로그인은 서비스 등록 후 사용할 수 있습니다. 직접 가입 또는 로그인해 주세요.`);return;}
 setBusy(true);try{const user=provider?await socialLogin(provider):await passwordLogin(email,password,signup);if(user){setPassword('');setMember(user);}}catch(error){setError(error instanceof Error?error.message:'로그인을 완료하지 못했습니다.');}finally{setBusy(false);}
 }
 return <KeyboardAvoidingView style={{flex:1,backgroundColor:'#F8F7F4'}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.auth}><Image source={artwork.lemoa} accessibilityLabel="르모아 로고" style={{width:72,height:72,borderRadius:18}}/><Text style={styles.title}>혜택을 모으는 시작,{ '\n'}르모아</Text><Text style={styles.copy}>{signup?'이메일과 비밀번호만으로 가입하세요.':'로그인하고 나에게 맞는 혜택을 확인하세요.'}</Text><TextInput accessibilityLabel={signup?'가입 이메일':'이메일 또는 관리자 ID'} placeholder={signup?'이메일':'이메일 또는 관리자 ID'} value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" autoComplete="email" style={styles.input}/><TextInput accessibilityLabel="비밀번호" placeholder={signup?'비밀번호 (10자 이상)':'비밀번호'} value={password} onChangeText={setPassword} secureTextEntry autoComplete={signup?'new-password':'current-password'} maxLength={128} style={styles.input}/><View style={styles.notice}><Text style={styles.copy}>직접 가입: 이메일·비밀번호 해시 (원문 미저장){ '\n'}소셜 가입: 서비스 구분·계정 식별자{ '\n'}목적: 가입 및 로그인 관리 / 보유: 회원탈퇴까지{ '\n'}이름·전화번호·생년월일·카드번호는 받지 않습니다.</Text><Pressable accessibilityRole="checkbox" accessibilityLabel="필수 정보 처리 안내 확인" accessibilityState={{checked:consent}} aria-checked={consent} onPress={()=>setConsent(!consent)} style={{paddingVertical:12}}><Text style={styles.copy}>{consent?'☑':'□'} [가입 시 필수] 위 정보 처리 안내를 확인했습니다.</Text></Pressable></View>{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<Action title={busy?'처리 중…':signup?'이메일로 회원가입':'로그인'} onPress={()=>void submit()} disabled={busy}/><Action title={signup?'이미 가입했어요 · 로그인':'이메일로 직접 회원가입'} secondary onPress={()=>{setSignup(!signup);setError('');setPassword('');}} disabled={busy}/><Text style={styles.copy}>소셜 계정으로 가입 / 로그인</Text><Action title={`네이버로 계속하기${config.providers.naver?'':' · 연결 준비 중'}`} secondary onPress={()=>void submit('naver')} disabled={busy}/><Action title={`구글로 계속하기${config.providers.google?'':' · 연결 준비 중'}`} secondary onPress={()=>void submit('google')} disabled={busy}/>{config.localAdmin&&<View style={styles.notice}><Text style={styles.copy}>이 PC의 관리자 테스트{ '\n'}ID: admin / Password: admin{ '\n'}실제 개인정보 없이 가게 확인 흐름을 테스트할 수 있어요.</Text></View>}</ScrollView></KeyboardAvoidingView>;
}
export const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',alignItems:'center',padding:24,gap:20},auth:{padding:28,paddingTop:48,width:'100%',maxWidth:480,alignSelf:'center',gap:16},title:{fontSize:27,lineHeight:38,fontWeight:'800',color:'#332E3D'},copy:{fontSize:14,lineHeight:23,color:'#766B82'},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#DED7E5',borderRadius:12,padding:16,fontSize:16,color:'#332E3D'},button:{backgroundColor:'#796292',minHeight:48,borderRadius:12,padding:14,justifyContent:'center',alignItems:'center'},buttonText:{fontSize:15,fontWeight:'700',color:'#FFF'},secondary:{backgroundColor:'#EFE9F5',borderWidth:1,borderColor:'#DED5E7'},notice:{backgroundColor:'#F1EDF5',padding:16,borderRadius:14,gap:8},error:{color:'#A22F43',fontSize:14,lineHeight:22}});
